### PR TITLE
ESP examples

### PR DESCRIPTION
**Pull request by Onno-Dirkzwager**
Added ESP(8266 & 32) examples as discussed here https://github.com/adafruit/Adafruit_DAP/issues/25#issuecomment-845522957

### CODE REVIEW

**Comment by Onno-Dirkzwager** [comment]
@hathach I think I understand what happened regarding the failed check. This is new to me... I'll study the githubci.yml & adafruit / ci-arduino files later today.

I understand I have to add the esp boards after the "metro_m4_tinyusb" in the .yml file. What I do not understand yet is how to set this up in a way that it is only used to test specific examples.

So the metro_m4_tinyusb for the existing examples.
And the esp32_dev_module fot the esp examples.

**Comment by hathach** [comment]
Thanks for the PR, the CI build failed since these 2 examples cannot be run by samd51. What you need to do is yeah adding esp target, but also need to add .test.only file  to each esp examples so that samd51 ci doesn't run it. Likewise, if there is any samd51 examples that esp cannot run, we have to add test.skip for esp as well

Sine you are new to our ci, you don't really have to do it, I will do it myself. Though I have another request in review comment.

**Review by hathach — COMMENTED** [review]
Since the ESP examples is unique and can only run on esp can you.
- Create new folder name **ESPHost** and put 2 examples inside this folder
- stm32_flash_from_ESP_SPIFFS should be rename to `flash_stm32_from_SPIFFS`
- flash_from_browser should be rename to `flash_samd51_from_web_browser`

Please also add a bit of text in the sketch e.g set up, how to upload (if there is examples with actual response would be great etc. Things could be easy but may not be obvious with other user.

**Comment by Onno-Dirkzwager** [comment]
@hathach thank you for the feedback. I'll follow and learn from your CI Build changes.
I made your recommended changes to the examples. Please let me know if theirs anything else I can do.

**Review by hathach — COMMENTED** [review]
Great, thanks for the changes. From the code the sketch should be named flash_samd21 instead of samd51. That is they are similar to each other and handled in the background. Though, let me know if this is a typo.

**Comment by Onno-Dirkzwager** [comment]
@hathach yes this was a typo, or rather a blind copy past from your suggestions ;)

**Comment by Onno-Dirkzwager** [comment]
Hi @hathach, 
There's no hurry, these are just examples! But I was wondering if there is anything I can do to help move this PR on. Or if you are waiting for action from my side?

**Comment by hathach** [comment]
Ah sorry, Everything look good, I am trying to ci passed them will merge asap

**Comment by Onno-Dirkzwager** [comment]
No problem! Just wanted to make sure that you were not waiting on me....

**Review by hathach — APPROVED** [review]
Every thing look good, thank you very much for your PRs.

**Comment by Onno-Dirkzwager** [comment]
Great! and thank you for making the CI compatible

**Pull request merged**
